### PR TITLE
Enhancement: Introducing Multi-Server Mode and `PUB/SUB` messaging patterns in NetGear API

### LINKED ISSUE #45: module 'zmq' has no attribute '0'
When I use NetGear, I got this error:   module 'zmq' has no attribute '0'
I install  pyzmp==17.1.2
numpy ==1.15.4
OpenCV-contirb-python==3.4.2.16
vidgear==0.1.5

And I run this server in container base ubuntu16.04

here is my code:
```
# import libraries
from vidgear.gears import NetGear
import cv2

stream = cv2.VideoCapture('hamilton_clip.mp4') #Open any video stream

options = {'flag': '0', 'copy': False, 'track': False}
#change following IP address '192.168.1.xxx' with yours
server = NetGear(address = '192.168.10.189', port = '5454', protocol = 'tcp',  pattern = 0, receive_mode = False, logging = True, **options) #Define netgear server at your system IP address.

# infinite loop until [Ctrl+C] is pressed
while True:
	try: 
		(grabbed, frame) = stream.read()
		# read frames

		# check if frame is not grabbed
		if not grabbed:
			#if True break the infinite loop
			break

		# do something with frame here

		# send frame to server
		server.send(frame)
	
	except KeyboardInterrupt:
		#break the infinite loop
		break

# safely close video stream
stream.release()
# safely close server
writer.close()
```
it come from netgear demo

### PR DESCRIPTION
**Pull request by abhiTronix**
## Description
This PR introduces robust and powerful **Multi-Server Mode & [Publish/Subscribe](https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pubsub.html)**(`zmq.PUB/zmq.SUB`)  messaging patterns for seamless Live Streaming over the network.

* **Multi-Server Mode:** In this exclusive mode, NetGear API can robustly handle multiple servers at once through exclusive Publish/Subscribe (zmq.PUB/zmq.SUB) messaging pattern thereby providing access to seamless Live Streams across the various device in a network at the same time. Each new Server on the network can be identified on the client's end by using its unique port address. Also, it exhibits a feature where if all the connected servers on the network get disconnected, the client itself automatically exits to save resources.

* **Publish/Subscribe Messaging Pattern:** is another classic pattern where senders of messages, called publishers, do not program the messages to be sent directly to specific receivers, called subscribers. Messages are published without the knowledge of what or if any subscriber of that knowledge exists. A ZMQ.SUB can connect to multiple ZMQ.PUB (publishers). No single publisher overwhelms the subscriber. The messages from both publishers are interleaved. Tip::bulb: This mode is best suited for Live Streaming.

### Changes:
- Implemented Robust Multi-Server Compatibility support in NetGear.
- Implemented new Publish/Subscribe (`zmq.PUB/zmq.SUB`) patterns for seamless Live Streaming.
- Added ability to send additional data along with the frame in realtime.
- Upgraded NetGear ability to handle any number of servers.
- Optimized overall real-time performance of NetGear.
- Updated ScreenGear to use Threaded Queue Mode by default.
- Removed redundant `THREADED_QUEUE_MODE` flag support from ScreenGear.
- Fixed #45 bugs
- Fixed various bugs related to these implementations.

### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/abhiTronix/vidgear/blob/master/contributing.md)
- [x] Read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting)
- [x] Comprehended the [Wiki Documentation](https://github.com/abhiTronix/vidgear/wiki#vidgear)
- [x] Updated the source-code documentation accordingly(if required).

### Fixes

#37
#45 

### Context

NetGear as of now does not support multiple server configuration. Moreover, current configurations only support blocking mode that either uses a `REQ/REP` or `PAIR/PAIR` zmq socket, in which either end would freeze until the other end is connected & start running for added synchronization. Unfortunately, this configuration is non-ideal for live-streaming as synchronization adds to latency in this mode. Therefore with this PR, I introduced  Robust Multi-Server Compatibility support in NetGear and added new Publish/Subscribe (`zmq.PUB/zmq.SUB`) patterns for seamless Live Streaming, therefore, providing usability to handle any number of servers easily. This PR also fixes various bugs with these implementations and bring some minor updates too.
### TODO
- [x] Update Docs
- [x] Fix additional bugs

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by xamarindevelopervietnam** [comment]
hi @abhiTronix this is great document https://github.com/abhiTronix/vidgear/wiki/Multi-Server-Mode-for-NetGear-API. I'm thinking that can Netgear send other data eg: date time, frame type ... go with camera frame. ZMQ  will send them with send multi parts function?

**Comment by abhiTronix** [comment]
@xamarindevelopervietnam Thanks for checking it out. I was working on other projects so didn't get the time to address you. 

> hi @abhiTronix this is great document https://github.com/abhiTronix/vidgear/wiki/Multi-Server-Mode-for-NetGear-API. I'm thinking that can Netgear send other data eg: date time, frame type ... go with camera frame. ZMQ will send them with send multi parts function?
> 
> Client will received dictionary extra data like this:
> extra_data, frame = data;
> unique_address = extra_data[unique_address];
> frame_type = extra_data[frame_type];

Yes, it is possible to send text with the frame but I left that part as it makes VidGear more complicated & the reason that VidGear is targetted for Video Processing only. I'll rethink about adding it but with a simpler approach.

**Comment by xamarindevelopervietnam** [comment]
I think it will be important part. Developer can use the others data to proceed frame from Camera.

**Comment by abhiTronix** [comment]
@xamarindevelopervietnam I'm super busy on another project. As soon as I'm free from it, I'll get this done.

**Comment by abhiTronix** [comment]
@xamarindevelopervietnam **Kindly test https://github.com/abhiTronix/vidgear/wiki/Multi-Server-Mode-for-NetGear-API#2-advanced-multi-server-mode-implementation-with-custom-message-transfer-and-filter-support , and don't forget to remove filter support as it is not required in our case and revert. Goodluck**

**Comment by xamarindevelopervietnam** [comment]
great! I hope this enhancement will be merged soon. I will add more enhancement ASAP.

**Comment by abhiTronix** [comment]
@xamarindevelopervietnam also Remember you can now send any type of data along with frame, for example,` dict, list, tuple,string, int` etc.

**Comment by xamarindevelopervietnam** [comment]
LOVE IT!

**Pull request merged**
