### PR TITLE
Enhancement: Introducing powerful ZMQ Authentication & Data Encryption features for NetGear API

### PR DESCRIPTION
**Pull request by abhiTronix**
## Description
_This PR introduces powerful, smart & secure ZeroMQ's Security Layers for NetGear API that enables strong encryption on data, and (_as far as we know_) unbreakable authentication between Servers and Client with the help of custom auth certificates/keys._ 

**This PR introduces supports for the two most powerful ZMQ security mechanisms:**

- **Stonehouse:** which switches to the _"CURVE"_ security mechanism, giving us strong encryption on data, and (as far as we know) unbreakable authentication. Stonehouse is the minimum you would use over public networks and assures clients that they are speaking to an authentic server while allowing any client to connect. **It is less secure but faster than IronHouse security mechanism.**
- **Ironhouse:** which extends Stonehouse with client public key authentication. This is the strongest security model we have today, protecting against every attack we know about, except end-point attacks (where an attacker plants spyware on a machine to capture data before it's encrypted, or after it's decrypted). **Its enhanced security comes at a price of additional latency.**

### Important Warnings
* **:warning: This feature only supports Python 3 and above, and also `libzmq` library version >= 4.0.**
* **:warning: IronHouse Security mechanism is the strongest security model, more secure than StoneHouse or any other security mechanisms, but its enhanced security comes at the price of added _LATENCY_.**

### TODO:
- [x] add exclusive `secure_mode` for enabling this feature
- [x] add support for powerful `Stonehouse` & `Ironhouse` ZMQ security mechanisms.
- [x] implement and test `Stonehouse` ZMQ security mechanism.
- [x] implement  and test `Ironhouse` ZMQ security mechanism.
- [x] robustly test compatibility with various modes and messaging patterns.
- [x] add smart auth certificates/key generation and validation
- [x] add additional dict params for enabling various tweaks.
- [x] fix bugs related to this implementation
- [x] Update docs

### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/abhiTronix/vidgear/blob/master/contributing.md)
- [x] Read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting)
- [x] Comprehended the [Wiki Documentation](https://github.com/abhiTronix/vidgear/wiki#vidgear)
- [x] Updated the source-code documentation accordingly(if required).

### Related Issue

#46 

### Context

As of now, NetGear API offers no data encryption, no authentication, and no privacy at all which makes it highly vulnerable to threats like a [man-in-the-middle attack (MITM)](https://en.wikipedia.org/wiki/Man-in-the-middle_attack).  To protect against it, one way is building your own physical networks and isolating it from the public Internet. However that is extraordinarily costly. Just as ZeroMQ brought us cheap, standardized connectivity for distributed systems, our goals with the security layers are to bring cheap, standardized privacy and authentication for distributed systems in NetGear API. Therefore, this PR introduces ZeroMQ's Security Layers for NetGear API that enables strong encryption on data, and (_as far as we know_) unbreakable authentication between Servers and Client with the help of custom auth certificates / keys generated at runtime.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Screenshots (if available):
None

### CODE REVIEW

**Comment by abhiTronix** [comment]
**@xamarindevelopervietnam Kindly test https://github.com/abhiTronix/vidgear/wiki/Secure-Mode:-Authentication-&-Data-Encryption-in-NetGear-API , and don't forget to remove filter support as it is not required in our case and revert your results. Goodluck**

**Comment by abhiTronix** [comment]
**@xamarindevelopervietnam Kindly test https://github.com/abhiTronix/vidgear/wiki/Secure-Mode:-Authentication-&-Data-Encryption-in-NetGear-API and revert your results. Goodluck**

**Comment by xamarindevelopervietnam** [comment]
@abhiTronix that's great, keep thinking about next question/enhancerment for VidGear

**Comment by xamarindevelopervietnam** [comment]
@abhiTronix could you define enum secure_mode?
eg: 
from enum import Enum
class SecureMode(Enum):
        Grassland = 0
        StoneHouse = 1
        IronHouse = 2
Then devs can use by:
options = {'secure_mode': SecureMode. IronHouse} #activates IronHouse Security Mechanism

**Comment by abhiTronix** [comment]
> from enum import Enum
> class SecureMode(Enum):
> Grassland = 0
> StoneHouse = 1
> IronHouse = 2
> Then devs can use by:
> options = {'secure_mode': SecureMode. IronHouse} #activates IronHouse Security Mechanism

@xamarindevelopervietnam Possible but not convenient for newbies due to following reasons:
- it will require extra dependency `enum34`or  `aenum` 
- python is case-sensitive language, so `IronHouse` will not be equal to `Ironhouse` or vice-versa. This will make it impossible to debug this error in a lengthy code.
- Also will add to complexity as we have to import new enum class to use it.
Finally, User always have freedom to use these useful hacks like this in their own code on top of vidgear anytime.

**Comment by xamarindevelopervietnam** [comment]
I have no idea!

**Comment by abhiTronix** [comment]
@xamarindevelopervietnam Does the Secure Mode example algorithm run smoothly on your machine, Or you find any error?

**Comment by xamarindevelopervietnam** [comment]
@abhiTronix do you use Skype/Whatsap/Telegram or any chat messenger?
I need to ask you some question about next enhancement. Thank you!

**Comment by abhiTronix** [comment]
> @abhiTronix do you use Skype/Whatsap/Telegram or any chat messenger?
> I need to ask you some questions about next enhancement. Thank you!

@xamarindevelopervietnam Sorry for the late reply, and I'm not currently active nor using any of the social app, But you can instead  mail me at abhi.una12@gmail.com We can talk over there.

**Comment by xamarindevelopervietnam** [comment]
thanks @abhiTronix

**Pull request merged**
