### PR TITLE
Fix some example code issues

### PR DESCRIPTION
**Pull request by iandol**
## Brief Description

I made 3 changes: (1) added a missing import (2) removed `self.` typo (3) removed the return value in the async as it triggers an error.

### Requirements / Checklist

- [x] I have read the [PR Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/PR/#submitting-pull-requestpr-guidelines).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).
- [x] I have updated the documentation accordingly(if required).

### Related Issue

#294 

### Context

Small tweak to the bonus example code.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

None of the above, its a small doc fix

### CODE REVIEW

**Comment by iandol** [comment]
@abhiTronix — you have asked to remove the edit to `return` — however if I revert it to `return None` then I get this Python error:

```
Diogenes » ↯3 …/gears on  main [!?] via 🐍 v3.10.2 
ⓔ ▷  python temp.py 
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ian/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/ian/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/ian/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 268, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 242, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "/Users/ian/Code/gears/temp.py", line 41
    return None
    ^^^^^^^^^^^
SyntaxError: 'return' with value in async generator
```

As I said, I am not a Python programmer, but searching for that error leads to this PEP: https://www.python.org/dev/peps/pep-0525/#specification — please confirm

**Comment by abhiTronix** [comment]
@iandol Yes, you're correct but here we don't need `return None`  and nor `return` but instead we need `break` which breaks loop and calls `client.close()`. So just change `return`  to `break` in your commit.

**Review by abhiTronix — CHANGES_REQUESTED** [review]
Change return to break in your commit.

**Review by abhiTronix — COMMENTED** [review]
LGTM! 🚀

**Comment by iandol** [comment]
Thanks for your patience and most excellent project!

**Pull request merged**
